name: async_content
description: A library that helps create screens that load content and work with a view model.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  extension_flutter_tools:
    path: /Users/mbritto/code/extension_flutter_tools
  extension_dart_tools:
    git: https://github.com/maxbritto/extension_dart_tools
    version: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^2.0.0
  test: ^1.21.0
